import "@/styles/globals.css";

import type { Metadata } from "next";

import SideNav from "@/components/layout/private/sideNav";
import TopBar from "@/components/layout/private/topBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex bg-emerald-50/30 h-screen">
      <SideNav></SideNav>
      <TopBar></TopBar>
      <div className="flex pl-64 pt-36 w-full">
        <div className="flex px-6 w-full">{children}</div>
      </div>
    </main>
  );
}
