import "@/styles/globals.css";
import "react-toastify/dist/ReactToastify.css";

import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";

import SideNav from "@/components/layout/private/sideNav";
import TopBar from "@/components/layout/private/topBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex bg-emerald-50/30 h-screen">
      <SideNav></SideNav>
      <div className="flex flex-col pl-64 w-full">
        <TopBar></TopBar>
        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <div className="flex px-10 w-full">{children}</div>
      </div>
    </main>
  );
}
