import "@/styles/globals.css";
import "react-toastify/dist/ReactToastify.css";

import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";

import SideNav from "@/components/layout/private/sideNav";
import TopBar from "@/components/layout/private/topBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="grid grid-cols-12 bg-gray-100 h-screen max-h-screen p-4">
      <SideNav></SideNav>
      <div className="flex flex-col w-full col-start-3 col-end-13 max-h-screen overflow-y-auto pl-10 pr-6">
        <TopBar></TopBar>
        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <div className="flex w-full justify-center">{children}</div>
      </div>
    </main>
  );
}
