import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Nav from "@/components/layout/nav";
import Footer from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light scroll-smooth">
      <body className={inter.className}>
        <Providers>
          <Nav></Nav>
          <main className="pt-20 grid grid-cols-12 min-h-screen">
            {children}
          </main>
          <Footer></Footer>
        </Providers>
      </body>
    </html>
  );
}
